#!/usr/bin/env bash

set -e

if [[ -n "$GOATCOUNTER_DEBUG" ]]; then
  set -x
fi

fail="no"

required_vars=(GOATCOUNTER_DB GOATCOUNTER_DOMAIN)
firstrun_vars=(GOATCOUNTER_EMAIL GOATCOUNTER_PASSWORD)

for var in "${required_vars[@]}"; do
  if [[ -z "${!var}" ]]; then
    echo "ERROR: Required environment variable \$${var} not set"
    fail="yes"
  fi
done

for var in ${firstrun_vars[@]}; do
  if [[ -z "${!var}" ]]; then
    echo "WARNING: First run environment variable \$${var} not set, this may fail"
  fi
done

if [[ "$fail" = "yes" ]]; then
  exit 1
fi

find_site() {
  goatcounter db show site\
    -db "$GOATCOUNTER_DB" \
    -createdb \
    -find "$GOATCOUNTER_DOMAIN"
}

create_site() {
  goatcounter db create site \
    -db "$GOATCOUNTER_DB" \
    -createdb \
    -vhost "$GOATCOUNTER_DOMAIN" \
    -user.email "$GOATCOUNTER_EMAIL" \
    -user.password "$GOATCOUNTER_PASSWORD"
}

# Create the site if it does not already exist
find_site || create_site

exec "$@"
