version: "3.8"

networks:
  web:
    external: true

volumes:
  caddy_storage:
  caddy_config:

services:
  nim-api:
    image: "aarowill/nim-api:latest"
    container_name: "nim-api"
    networks:
      - web
    depends_on:
      - "nim-caddy"
    restart: always
  nim-analytics:
    image: "aarowill/nim-analytics:latest"
    container_name: "nim-analytics"
    networks:
      - web
    depends_on:
      - "nim-caddy"
    restart: always
    volumes:
      - ./analytics/db:/goatcounter/db
    env_file: ./analytics/production.env
  nim-caddy:
    image: "aarowill/nim-caddy:latest"
    container_name: "nim-caddy"
    networks:
      - web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_storage:/data
      - caddy_config:/config
